import { describe, it, expect } from 'vitest';
import { stripAiAttribution } from '../attributionPatterns.js';

describe('stripAiAttribution', () => {
  it('leaves prose that merely mentions the phrase untouched', () => {
    // Regression test: an earlier version of the fallback regex matched
    // "Generated by Claude Code" anywhere in a line, not just at its start,
    // and silently deleted this exact sentence from a real commit message.
    const input =
      'Manually stripping the "Generated by Claude Code" PR footer after every create_pull_request call works fine.';
    expect(stripAiAttribution(input)).toBe(input + '\n');
  });

  it('strips a real emoji-prefixed PR footer plus a trailing bare session link', () => {
    const input =
      'Body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_x';
    const out = stripAiAttribution(input);
    expect(out).toBe('Body.\n');
  });

  it('strips a real underscore-wrapped footer with a divider rule', () => {
    const input = 'Body.\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_x)_';
    expect(stripAiAttribution(input)).toBe('Body.\n');
  });

  it('strips a Co-Authored-By trailer', () => {
    const input = 'fix: x\n\nCo-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>';
    expect(stripAiAttribution(input)).toBe('fix: x\n');
  });

  it('strips a Claude-Session trailer', () => {
    const input = 'fix: x\n\nClaude-Session: https://claude.ai/code/session_01Abc';
    expect(stripAiAttribution(input)).toBe('fix: x\n');
  });

  it('leaves a plain, clean commit message unchanged', () => {
    const input = 'fix: normal commit\n\nJust a normal body, no attribution at all.';
    expect(stripAiAttribution(input)).toBe(input + '\n');
  });

  it('round-trips the real multi-line body that regressed once, keeping every prose line', () => {
    const input = [
      'chore: enforce no-AI-attribution automatically, everywhere',
      '',
      'Manually stripping the "Generated by Claude Code" PR footer after every',
      'create_pull_request call works, but only for PRs a session remembers to',
      'clean up by hand.',
      '',
      'Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>',
      'Claude-Session: https://claude.ai/code/session_01JyqFdkw4BG6LoJNykh1HHR',
      '',
    ].join('\n');
    const out = stripAiAttribution(input);
    expect(out).toContain(
      'Manually stripping the "Generated by Claude Code" PR footer after every',
    );
    expect(out).toContain(
      'create_pull_request call works, but only for PRs a session remembers to',
    );
    expect(out).not.toContain('Co-Authored-By');
    expect(out).not.toContain('claude.ai');
  });

  it('returns falsy input unchanged', () => {
    expect(stripAiAttribution('')).toBe('');
  });
});
